// This file is auto-generated by @hey-api/openapi-ts


export const $ClusterPublic = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        representative_face: {
            '$ref': '#/components/schemas/FacePublicWithXY'
        }
    },
    type: 'object',
    required: ['id', 'representative_face'],
    title: 'ClusterPublic'
} as const;

export const $FaceClusterAssignment = {
    properties: {
        face_id: {
            type: 'string',
            title: 'Face Id'
        },
        cluster_id: {
            type: 'integer',
            title: 'Cluster Id'
        }
    },
    type: 'object',
    required: ['face_id', 'cluster_id'],
    title: 'FaceClusterAssignment'
} as const;

export const $FacePublic = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        image_path: {
            type: 'string',
            title: 'Image Path'
        },
        x: {
            type: 'number',
            title: 'X'
        },
        y: {
            type: 'number',
            title: 'Y'
        },
        w: {
            type: 'number',
            title: 'W'
        },
        h: {
            type: 'number',
            title: 'H'
        }
    },
    type: 'object',
    required: ['id', 'image_path', 'x', 'y', 'w', 'h'],
    title: 'FacePublic'
} as const;

export const $FacePublicWithXY = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        image_path: {
            type: 'string',
            title: 'Image Path'
        },
        x: {
            type: 'number',
            title: 'X'
        },
        y: {
            type: 'number',
            title: 'Y'
        },
        w: {
            type: 'number',
            title: 'W'
        },
        h: {
            type: 'number',
            title: 'H'
        },
        embedding_x: {
            type: 'number',
            title: 'Embedding X'
        },
        embedding_y: {
            type: 'number',
            title: 'Embedding Y'
        }
    },
    type: 'object',
    required: ['id', 'image_path', 'x', 'y', 'w', 'h', 'embedding_x', 'embedding_y'],
    title: 'FacePublicWithXY'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $ImageClusterAssignment = {
    properties: {
        image_path: {
            type: 'string',
            title: 'Image Path'
        },
        cluster_id: {
            type: 'integer',
            title: 'Cluster Id'
        },
        face_id: {
            type: 'string',
            title: 'Face Id'
        }
    },
    type: 'object',
    required: ['image_path', 'cluster_id', 'face_id'],
    title: 'ImageClusterAssignment'
} as const;

export const $MergeClustersRequest = {
    properties: {
        cluster_ids: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Cluster Ids'
        }
    },
    type: 'object',
    required: ['cluster_ids'],
    title: 'MergeClustersRequest'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;