// This file is auto-generated by @hey-api/openapi-ts


import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './types.gen';

export class DefaultService {
    /**
 * Add Images From Folder
 * @returns unknown Successful Response
 * @throws ApiError
 */
    public static addImagesFromFolder(data: $OpenApiTs['/addImagesFromFolder']['post']['req']): CancelablePromise<$OpenApiTs['/addImagesFromFolder']['post']['res'][200]> {
        const { imagesDir } = data;
        return __request(OpenAPI, {
    method: 'POST',
    url: '/addImagesFromFolder',
    query: {
        images_dir: imagesDir
    },
    errors: {
        422: 'Validation Error'
    }
});
    }
    
    /**
 * Initialize Clusters
 * @returns unknown Successful Response
 * @throws ApiError
 */
    public static initializeClusters(data: $OpenApiTs['/initializeClusters']['post']['req']): CancelablePromise<$OpenApiTs['/initializeClusters']['post']['res'][200]> {
        const { minSamples, minClusterSize } = data;
        return __request(OpenAPI, {
    method: 'POST',
    url: '/initializeClusters',
    query: {
        min_samples: minSamples,
        min_cluster_size: minClusterSize
    },
    errors: {
        422: 'Validation Error'
    }
});
    }
    
    /**
 * Get Clusters
 * @returns ClusterPublic Successful Response
 * @throws ApiError
 */
    public static getClusters(): CancelablePromise<$OpenApiTs['/clusters']['get']['res'][200]> {
        return __request(OpenAPI, {
    method: 'GET',
    url: '/clusters'
});
    }
    
    /**
 * Reset Clusters
 * @returns unknown Successful Response
 * @throws ApiError
 */
    public static resetClusters(): CancelablePromise<$OpenApiTs['/clusters']['delete']['res'][200]> {
        return __request(OpenAPI, {
    method: 'DELETE',
    url: '/clusters'
});
    }
    
    /**
 * Get Face Cluster Assignments
 * @returns FaceClusterAssignment Successful Response
 * @throws ApiError
 */
    public static getFaceClusterAssignments(): CancelablePromise<$OpenApiTs['/faceClusterAssignments']['get']['res'][200]> {
        return __request(OpenAPI, {
    method: 'GET',
    url: '/faceClusterAssignments'
});
    }
    
    /**
 * Get Image Cluster Assignments
 * @returns ImageClusterAssignment Successful Response
 * @throws ApiError
 */
    public static getImageClusterAssignments(): CancelablePromise<$OpenApiTs['/imageClusterAssignments']['get']['res'][200]> {
        return __request(OpenAPI, {
    method: 'GET',
    url: '/imageClusterAssignments'
});
    }
    
    /**
 * Get Faces
 * @returns FacePublic Successful Response
 * @throws ApiError
 */
    public static getFaces(): CancelablePromise<$OpenApiTs['/faces']['get']['res'][200]> {
        return __request(OpenAPI, {
    method: 'GET',
    url: '/faces'
});
    }
    
    /**
 * Get Image
 * @returns unknown Successful Response
 * @throws ApiError
 */
    public static getImage(data: $OpenApiTs['/image']['get']['req']): CancelablePromise<$OpenApiTs['/image']['get']['res'][200]> {
        const { filePath, width, cache, x, y, w, h } = data;
        return __request(OpenAPI, {
    method: 'GET',
    url: '/image',
    query: {
        filePath,
        width,
        cache,
        x,
        y,
        w,
        h
    },
    errors: {
        422: 'Validation Error'
    }
});
    }
    
    /**
 * Merge Clusters
 * @returns unknown Successful Response
 * @throws ApiError
 */
    public static mergeClusters(data: $OpenApiTs['/mergeClusters']['post']['req']): CancelablePromise<$OpenApiTs['/mergeClusters']['post']['res'][200]> {
        const { requestBody } = data;
        return __request(OpenAPI, {
    method: 'POST',
    url: '/mergeClusters',
    body: requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
});
    }
    
    /**
 * Get Projects
 * @returns string Successful Response
 * @throws ApiError
 */
    public static getProjects(): CancelablePromise<$OpenApiTs['/projects']['get']['res'][200]> {
        return __request(OpenAPI, {
    method: 'GET',
    url: '/projects'
});
    }
    
    /**
 * Switch Project
 * @returns unknown Successful Response
 * @throws ApiError
 */
    public static switchProject(data: $OpenApiTs['/projects/{project_name}']['get']['req']): CancelablePromise<$OpenApiTs['/projects/{project_name}']['get']['res'][200]> {
        const { projectName } = data;
        return __request(OpenAPI, {
    method: 'GET',
    url: '/projects/{project_name}',
    path: {
        project_name: projectName
    },
    errors: {
        422: 'Validation Error'
    }
});
    }
    
    /**
 * Get Images
 * @returns string Successful Response
 * @throws ApiError
 */
    public static getImages(): CancelablePromise<$OpenApiTs['/images']['get']['res'][200]> {
        return __request(OpenAPI, {
    method: 'GET',
    url: '/images'
});
    }
    
}