// This file is auto-generated by @hey-api/openapi-ts


export type ClusterPublic = {
    id: number;
    representative_face: FacePublicWithXY;
};

export type FaceClusterAssignment = {
    face_id: string;
    cluster_id: number;
};

export type FacePublic = {
    id: string;
    image_path: string;
    x: number;
    y: number;
    w: number;
    h: number;
};

export type FacePublicWithXY = {
    id: string;
    image_path: string;
    x: number;
    y: number;
    w: number;
    h: number;
    embedding_x: number;
    embedding_y: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ImageClusterAssignment = {
    image_path: string;
    cluster_id: number;
    face_id: string;
};

export type MergeClustersRequest = {
    cluster_ids: Array<(number)>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type $OpenApiTs = {
    '/addImagesFromFolder': {
        post: {
            req: {
                imagesDir: string;
            };
            res: {
                /**
 * Successful Response
 */
                200: unknown;
            };
        };
    };
    '/initializeClusters': {
        post: {
            req: {
                minClusterSize: number;
                minSamples: number;
            };
            res: {
                /**
 * Successful Response
 */
                200: unknown;
            };
        };
    };
    '/clusters': {
        get: {
            res: {
                /**
 * Successful Response
 */
                200: Array<ClusterPublic>;
            };
        };
        delete: {
            res: {
                /**
 * Successful Response
 */
                200: unknown;
            };
        };
    };
    '/faceClusterAssignments': {
        get: {
            res: {
                /**
 * Successful Response
 */
                200: Array<FaceClusterAssignment>;
            };
        };
    };
    '/imageClusterAssignments': {
        get: {
            res: {
                /**
 * Successful Response
 */
                200: Array<ImageClusterAssignment>;
            };
        };
    };
    '/faces': {
        get: {
            res: {
                /**
 * Successful Response
 */
                200: Array<FacePublic>;
            };
        };
    };
    '/image': {
        get: {
            req: {
                cache?: boolean;
                filePath: string;
                h?: number;
                w?: number;
                width?: number;
                x?: number;
                y?: number;
            };
            res: {
                /**
 * Successful Response
 */
                200: unknown;
            };
        };
    };
    '/mergeClusters': {
        post: {
            req: {
                requestBody: MergeClustersRequest;
            };
            res: {
                /**
 * Successful Response
 */
                200: unknown;
            };
        };
    };
    '/projects': {
        get: {
            res: {
                /**
 * Successful Response
 */
                200: Array<(string)>;
            };
        };
    };
    '/projects/{project_name}': {
        get: {
            req: {
                projectName: string;
            };
            res: {
                /**
 * Successful Response
 */
                200: unknown;
            };
        };
    };
    '/images': {
        get: {
            res: {
                /**
 * Successful Response
 */
                200: Array<(string)>;
            };
        };
    };
};